### ISSUE TITLE
Not working in Unity 2019.4.40 LTS

### ISSUE THREAD

**Issue by paulorenanmelo** [5argon/NotchSolution#67]
Error when importing package, not compiling.

> Library\PackageCache\com.e7.notch-solution@35d64ddef6\Editor\Simulator\NotchSimulator.cs(433,55): error CS0246: The type or namespace name 'PrefabStage' could not be found (are you missing a using directive or an assembly reference?)

**Comment by sdalexandre** [comment]
The breaking changes:
https://github.com/5argon/NotchSolution/commit/2bb581e20dfc5f666a9819af86bed2962ffa9d76

I have solved the error by readding the following line:
using UnityEditor.Experimental.SceneManagement;
